Hoh_data_Discrim= ["The Racial & Religious Hatred Act 2006 received royal assent ",
"reinforcing Islamophobia ",
"There was a vulnerability of Muslims to physical violence and harassment",
"the consequence of this kind of violence for Muslims was that they were unable to play a full part in mainstream society",
"Church of England enjoyed protection from the law of blasphemy",
"some other religious groups in the UK enjoyed protection from the law in other significant areas",
"The Race Relations Act 1976 (RRA 76) provided protection against discrimination on the grounds of the statutory definition of racial group",
"mono-ethnic faith communities like the Sikh and Jewish communities were protected from discrimination",
"they benefited from a positive duty on public authorities to promote equality",
"protected from aggravated offences of harassment violence and criminal damage motivated by racial hatred",
"incitement of such hatred",
"making the fight against racism stronger",
"many injustices and anomalies would arise as a result",
"legislation could be used against the very minority communities it was to protect",
"towards reducing and deterring anti-Muslim violence",
"their religious buildings and spaces faced a higher risk of crime",
"this was a distinct and deeper form of harm ",
"it specifically targeted Muslims because of their membership of a religious group",
"they also caused additional and distinct harms to the whole Muslim community",
"the crime was seen as an attack on the whole religious group ",
"the increasing risks of physical and verbal abuse of Muslims ",
"commit acts of violence and harassment of Muslims out of deliberate and conscious hatred ",
"will receive a higher penalty under the criminal law",
"there was a substantial risk that Muslims would disproportionately become the victims ",
"it must provide certain safeguards to ensure that the discretion of law enforcement agencies is not abused to target Muslims",
"this may in turn exacerbate existing tensions between law enforcement agencies and Muslim communities ",
"minimise the risk of further conflict between them",
"the exercise of discretion by law enforcement agencies was monitored and accountable",
"law enforcement agencies should be supervised monitored and held accountable ",
"the duty on courts to read legislation so far as possible to be compatible with Convention rights",
"harassment violence and or criminal damage to property resulting from such incitement",
"Incitement of Racial Hatred",
"publish insulting or abusive words with the intent to stir up racial hatred ",
"racial hatred is likely to be stirred up as a result of the action",
"The definition of racial group is extended by case law ",
"violence and or criminal damage to property motivated by religious hatred",
"left to the Courts to define should the occasion arise for such a definition",
"The Act extends the provisions entailed in the Crime & Disorder Act",
"which in turn incited others to abuse harass and assault Muslims",
"the clearest legal duty to consider equality in public procurement was provided by the public sector race equality duty",
"had in some cases even led to localised disturbances ",
"UK stood in breach of its obligations under the European Convention of Human Rights",
"the right to freedom of expression is guaranteed by Article 10",
"the need to balance incitement with freedom of expression",
"cases of incitement to religious hatred could be covered under existing common law on incitement ",
"Attorney Generals fiat could be politically abused",
"being exploited by the far right to create tensions between communities",
"members of faith communities have an Article 9 right to be protected from incitement of religious hatred",
"tackle public disorder and safety issues",
"the longer these vulnerable communities are exposed to harm and the greater the risk",
"Government was indeed in breach of its obligations under Article 9 read with Article 14",
"displays any written material which is threatening abusive or insulting is guilty of an offence",
"intends thereby to stir up racial or religious hatred",
"likely to stir up racial or religious hatred",
"Public Order Act 1986 incorporated the criminal offence of incitement to racial hatred",
"the social exclusion and isolation of Muslims ",
"institutional discrimination within law enforcement agencies",
"the same safeguards and reporting arrangements that apply to the prosecution of cases of racial violence will apply ",
"offence of incitement to hatred on grounds of religion or belief",
"The protection is focused more on the religion rather than the individual follower of the religion",
"the protection they provide uniquely to the Anglican Church",
"challenged by the Police or the Courts ",
"interpretation of the terms should be consistent with the approach adopted by the European Court of Human Rights in relation to the Convention",
"sought to tackle all grounds of unfair discrimination in all spheres of activity",
"it extended the positive duty requirements of the Race Relations Amendment  Act 2000 beyond race to all the grounds",
"extra burden on the victim and was a regression from the Directive",
"governments recognition that unfair discrimination has a damaging effect far beyond any immediate discriminatory practices",
"basic requirements in law are necessary to curtail such negative and damaging impact on peoples lives",
"the right to religion is guaranteed under the Human Rights Act",
"The duty required public bodies to have due regard to the need to eliminate unlawful racial discrimination",
"public bodies had to ensure that when they spent public money it was not supporting unlawful discrimination",
"encouraging and supporting the promotion of race equality",
"government should promote the incorporation of race equality into public procurement within current legal and policy frameworks",
"intensification of political violence in the 1960s",
"the communal violence escalated",
"only sixteen were later charged with criminal offences",
"The Prevention of Terrorism",
"There were also significant attacks in Europe",
"multiple attacks on the Madrid train network in March 2004",
"simultaneous explosions on the Underground network and a bus in London killed 52 people",
"requirements for avoiding risks to health and safety",
"the Government was forced to respond to the ruling in the Belmarsh cases by repealing legislation on the detention of foreign nationals",
"was held to be incompatible by the European Court of Human Rights",
"Commission has been  taking initiatives to combat racism",
"The departments remained responsible for achieving their PSA targets",
"To bring about measurable improvements in race equality",
"to investigate internet-based content which might be illegal under UK law and to take appropriate action",
"Additionally the government pursued strategic prosecutions",
"it signalled very clearly that the Muslim right to the provision of education within its religious ethos was to be respected",
"It not only signalled the right to religious accommodation and meeting of religious needs",
"Although serious discriminatory practices on the basis of religion were genuine and real there were few safeguards against them",
"the curtailment of certain rights through the Anti-Terrorism, Crime & Security Act 2001",
"the new commission will prepare the ground for a single Equality Act as one of its first major tasks",
"The Discrimination Law Review was to consider the opportunities for creating a simpler fairer and more streamlined equality legislation framework in a Single Equality Act",
"was required to use contract conditions to make sure that the contractor did not discriminate unlawfully",
"was recruited and managed in ways that are consistent with the public bodys equality duties",
"the subject of the contract could itself impose equality requirements",
"the specification for the provision of sexual health counselling services could require the contractor to try to employ both men and women as counsellors to account for cultural sensitivities",
"how the public body builds race equality into each stage in ways that are compatible with EU rules",
"Every public body with statutory duties to eliminate discrimination and to promote equality was required to use contract conditions to make sure that the contractor did not discriminate unlawfully",
"New Labour struck a strategic relationship with the newly formed Muslim Council of Britain ",
"The key advocates for this legislation have in the main been British Muslim communities ",
"The leadership took some time learning to do this effectively",
"first presented by the An-Nisa submission",
"This was most notably captured by a landmark report ",
"convened a year earlier by the Runnymede Trust",
"The report also presented in clear English the evidence it had gathered ",
"examining the role of the media ",
"presented in the Runnymede Trust report",
"subsequently bolstered by a string of other research and publications",
"the picture was made all the clearer after the 2001 Census question on religion",
"additional research and Census findings suggested ",
"The essence of the effort was captured in a leaflet produced by a consortium ",
"The leaflet argued ",
"it was enthusiastically campaigned for",
"it was received with far more caution and deliberation",
"arguing on occasions that religions should not be ethnicised but allowed to stand on their own",
"the briefing paper further suggested",
"highlighted the exercise of discretion concerns ",
"the briefing further pointed towards concerns ",
"after considerable discussion in the Muslim communities on the proposal ",
"Muslims had previously campaigned ",
"the consortium stressed that it nonetheless had significant reservations about including the extension ",
"The consortium highlighted evidence indicating existing low levels of satisfaction amongst ethnic minorities ",
"advised that it would be in the interests of the State",
"broke away from the rest of the consortium",
"appeared to be significantly more opposition to this provision ",
"The proposal was however revived ",
"courts may give higher penalties ",
"not to advocate for its extension or abolishment",
"ready to accept that where that was not possible for practical reasons",
"the campaign was sustained with full vigour ",
"several other key Muslim organisations submitted their written evidence",
"this was subsequently reinforced and augmented by further oral evidence",
"providing copious references to literature ",
"religion is based on choice of beliefs values and practices",
"able to use it as a basis to galvanise a strong alliance of leaders ",
"strong public statement in support of new legislation ",
"it was widely claimed that the Bill was an inappropriate vehicle ",
"gave no indication of any commitment to a timeframe",
"stating only that it will seek to bring legislation ",
"demand for this in the face of an upcoming election",
"The proposal was quickly supported by another alliance ",
"The proposal was further endorsed on 13 January 2005 ",
"it still attracted significant opposition from various quarters",
"all of whom were concerned about the limitations ",
"regarded by himself and some others as the father of equality provisions",
"The discussions eventually broke down ",
"with an election promise ",
"opposition expressed in response to the previous attempts ",
"resulted in a sustained opposition",
"two successive votes ",
"dramatically narrowed the scope ",
"very significantly watered down from what was intended",
"concluded with sixty recommendations",
"drive the changes in public opinion required ",
"the leaflet cited some graphic examples ",
"undermined the group and its expert understanding ",
"it pointed out that there was no principled distinction between race and religion in this instance",
"a submission from a consortium ",
"slipped out of sight",
"evident in how it dealt with the proposals ",
"the community had not quite given up",
"its approach was more politically mature",
"there appeared to be a different tone and approach to the proposed provisions",
"on this occasion positively advocated the need to support such legislation",
"religion as choice and therefore needing to be open to criticism",
"working very closely with the other Muslim organisations",
"the Bill intended to go beyond the minimum provisions",
"the Bill sought to set out a single framework",
"it laid out the details of its main concern",
"the Bill was thus introduced in Parliament",
"it was introduced in the House of Lords",
"the Bill had undermined its key objective",
"it was important to bear in mind that this Bill had been initiated by the Liberal Democrats",
"the Government was not supporting the initiative",
"would allow the Government to discredit the Bill",
"his would be a useful strategy to show unity with others on the greater cause",
"win support for an overall framework",
"filled with specific detail based on particular needs",
"to place a few strategic amendments",
"to promote discussions on the other policy concerns",
"reiterated that the distinction being drawn between philosophical belief and political belief was not helpful",
"suggesting that it ought perhaps to do so",
"it welcomed the proposal to harmonise the burden of proof",
"this Taskforce was to be filled by a Muslim appointed by the Secretary of State for the Department of Trade and Industry",
"It was to recommend the introduction of new law and procedures to deal with changes to the terrorist threat",
"many refusing to accept the government’s assessment of the level of the threat from terrorism",
"On closely examining this literature FAIR concluded",
"The report did not make any specific recommendations",
"Separate from this case made on the basis of the overlap between race and religion",
"BMRC urged that the Bill treated all the strands of discrimination including religion consistently",
"Muslims were also concerned",
"In a strongly worded letter from the Secretary General",
"This was further reinforced through a meeting and exchanges",
"acknowledging the strong response from the MCB and its persuasiveness",
"if they chose to enter into contracts with a public body",
"The Muslim Council of Britain was invited to provide a representative",
"it feels very much that it is finding reasons to justify the status quo",
"a cross departmental approach to capacity building in the departments and the communities"
]
