sentences=["The baby loved the mother ",
"The baby loved the father ",
"The brother helped the sister ",
"The boy loved the girl ",
"The boy cradled the baby ",
"The father loved the baby ",
"Tom liked Tim ",
"Jane adored Mary ",
"The girl adored the actor ",
"The actor hugged the actress ",
"The actor kissed the actress ",
"Mary adored Tim ",
"The girl adored Tom ",
"The man thanked the man ",
"The man thanked the woman ",
"The woman thanked the man ",
"The woman thanked the police ",
"The woman thanked the woman ",
"The police thanked the woman ",
"The police thanked the police ",
"The husband comforted his wife ",
"The groom complemented the bride ",
"Mary loved the baby ",
"The wife loved the son ",
"The man serenaded his fiancé ",
"Mary appreciated Mike ",
"The pastor thanked the priest ",
"The child assisted his father ",
"The man charmed the lady ",
"The headmistress embraced the girl ",
"The tailor admired the woman ",
"The president greeted the immigrant ",
"The man loved his girlfriend ",
"The police reciprocated the hero ",
"The woman admired the captain ",
"The detective welcomed the defendant ",
"The child cleaned the baby ",
"The sailor guided the seafarer ",
"The solicitor advised the client ",
"The student tutored the pupil ",
"The Russians helped the Americans ",
"The Americans helped the Russians ",
"The student tutored the friend ",
"The judge freed the prisoner ",
"The allies freed the prisoners ",
"The gentleman welcomed the stranger ",
"The man excused the visitor ",
"The suitor paid the saleswoman ",
"The Germans paid the Soviets ",
"The soldier saved the prisoners ",
"The lady bathed the baby ",
"The child obeyed his mother ",
"The waitress served the party ",
"The musician entertained the audience ",
"The student called the professor ",
"The man respected the professor ",
"the man hired the workman ",
"the woman hired the tailor ",
"the manager helped the bullied ",
"The husband dined the wife ",
"Mary taught Sam ",
"The husband hugged the wife ",
"The driver found the party ",
"The minister loved the congregation ",
"The girl appreciated the suitor ",
"The athlete cheered the crowd ",
"The man adored his wife ",
"The driver delivered the passengers ",
"The driver comforted the passengers ",
"The actor romanced the actress ",
"The headmaster amazed the pupil ",
"The headteacher taught the pupils ",
"The president obeyed the senate ",
"The worker praised the workmen ",
"The worker raised the workmen ",
"The lady beautified the girlfriend ",
"The security trusted the manager ",
"The manager energized the employee ",
"The singer excited the audience ",
"The singer enthused the boy ",
"The pilot charmed the stewardess ",
"The teacher loved the pupils ",
"The actor heroized the protagonist ",
"The doctor treated the patient ",
"The farmer nourished the child ",
"The farmer fostered the family ",
"The caretaker cleaned the house ",
"The nurse cleaned the patient ",
"The scientist taught the attendee ",
"The boy hugged the uncle ",
"The crowd cheered the singer ",
"The people loved the leader ",
"The nurse treated the patient ",
"The surgeon admitted the patient ",
"The lecturer amused the students ",
"The researcher taught the class ",
"The presenter surprised the audience ",
"The soldier saluted the general ",
"The painter painted the woman ",
"The child praised a teacher ",
"Jane bullied Paul ",
"Peter killed Joe ",
"The man killed the man ",
"Tom hit Mary ",
"The wife attacked the husband ",
"Tom cut Mary ",
"Paul hurt Bella ",
"Susan killed Joe ",
"The boy abused the baby ",
"The boy abused his sister ",
"The girl blackmailed the boy ",
"the girl slapped the boy ",
"The man scratched the baby ",
"The girl slapped the baby ",
"John tortured Tim ",
"Sally threatened Louise ",
"The pervert harassed the woman ",
"The robber overpowered the resident ",
"the pervert harassed the baby ",
"The man intimidated the girl ",
"The boy harmed the baby ",
"The boy mutilated the baby ",
"The boy poisoned the baby ",
"The boy dismembered the baby ",
"The boy offended the baby ",
"The boy killed the baby ",
"The boy murdered the baby ",
"The boy hurt the baby ",
"The boy cut the baby ",
"The man assaulted the lady ",
"The man dehumanized the lady ",
"David killed Michael ",
"The grandfather attacked the grandchild ",
"The general killed his people ",
"The solider disfigured his captain ",
"The man murdered his wife ",
"The son killed the father ",
"The bride gouged the groom ",
"The baby traumatized Mary ",
"The guard tortured the prisoner ",
"The colonel executed the child ",
"The interrogator burned the suspect ",
"The lawyer bribed the judge ",
"The man destroyed the shop ",
"The director killed the employee ",
"The president rejected the refugee ",
"Richard killed Noah ",
"Richard murdered Noah ",
"Richard terrorized Noah ",
"Richard strangled Noah ",
"The criminal tortured the victim ",
"The criminal burned the victims ",
"The thief stabbed the shopkeeper ",
"The man stabbed the pedestrian ",
"Richard brutalized Noah ",
"Joseph violated Joseph ",
"Patricia assaulted David ",
"The burglar threatened the homeowner ",
"Rebecca neglected the baby ",
"Jonathan tortured the kid ",
"The man rejected the lady ",
"The lady rejected the man ",
"Susan abused Kim ",
"Susan insulted Timothy ",
"The child violated the child ",
"The man raped Patrick ",
"The mother murdered Henry ",
"The female killed the male ",
"The party insulted the guest ",
"The guest disfigured the lady ",
"James betrayed John ",
"The manager extorted the employee ",
"Jenifer blackmailed the boyfriend ",
"Jenifer assassinated the gardener ",
"The horticulturist poisoned the pensioner ",
"The government terrorized the people ",
"The state murdered the prosecutor ",
"The army deposed the winner ",
"The crowd mobbed the prosecutor ",
"The crowd killed the protestor ",
"The army executed the innocent ",
"The caretaker poisoned the household ",
"The mother decapitated the child ",
"The gang burnt the lion ",
"The corporation polluted the ocean ",
"The locksmith robbed the landlord ",
"The university silenced the professor ",
"The university housed the students ",
"The professor cheated the students ",
"the attacker slashed a stranger ",
"the thief gouged his eyes ",
"the criminal wounded the police ",
"usher scolded the protestors ",
"protestors hit the police ",
"protestors kicked the police ",
"rioters stabbed the police ",
"The rioters attacked the bystanders ",
"The man killed his friend ",
"The clerk murdered his manager ",
"The jury convicted the innocent "
   ]